version: "3.9"

services:
  app:
    container_name: app_container
    image: golang/1.17.7
    environment:
      RUN_ADDRESS: "${RUN_ADDRESS}"
      ACCRUAL_SYSTEM_ADDRESS: "${ACCRUAL_SYSTEM_ADDRESS}"
      DATABASE_URI: "${DATABASE_URI}"
    build:
      dockerfile: cmd/gophermart/Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - diploma

  accrual:
    container_name: accrual_container
    environment:
      RUN_ADDRESS: "${ACCRUAL_SYSTEM_ADDRESS}"
    build:
      dockerfile: cmd/accrual/Dockerfile
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - diploma

  postgres:
    container_name: postgres_container
    image: postgres:14.1
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      diploma:
        aliases:
          - postgres

  migrate:
    container_name: migrate_container
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [ "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - diploma

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - diploma

networks:
  diploma:
    driver: bridge
