version: "3.9"

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_DB: "yandex-diploma"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "Qwerty!234"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d yandex-diploma" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
