// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	users "github.com/magmel48/go-musthave-diploma/internal/users"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *Repository) Create(user users.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(users.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields:
func (_m *Repository) Find() *users.User {
	ret := _m.Called()

	var r0 *users.User
	if rf, ok := ret.Get(0).(func() *users.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	return r0
}
