// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	orders "github.com/magmel48/go-musthave-diploma/internal/orders"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: order
func (_m *Repository) Create(order orders.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(orders.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
