// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	balances "github.com/magmel48/go-musthave-diploma/internal/balances"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Change provides a mock function with given fields: ctx, userID, amount
func (_m *Repository) Change(ctx context.Context, userID int64, amount float64) error {
	ret := _m.Called(ctx, userID, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64) error); ok {
		r0 = rf(ctx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUser provides a mock function with given fields: ctx, userID
func (_m *Repository) FindByUser(ctx context.Context, userID int64) (*balances.Balance, error) {
	ret := _m.Called(ctx, userID)

	var r0 *balances.Balance
	if rf, ok := ret.Get(0).(func(context.Context, int64) *balances.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*balances.Balance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
