// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	accrual "github.com/magmel48/go-musthave-diploma/internal/accrual"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetOrder provides a mock function with given fields: ctx, orderNumber
func (_m *Service) GetOrder(ctx context.Context, orderNumber string) (*accrual.OrderResponse, error) {
	ret := _m.Called(ctx, orderNumber)

	var r0 *accrual.OrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *accrual.OrderResponse); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accrual.OrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
